apiVersion: v1
kind: Service
metadata:
  name: auth-frontend-service
  namespace: central-oondemand
spec:
  type: NodePort
  selector:
    app: auth-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
