apiVersion: v1
kind: Service
metadata:
  name: auth-frontend-homolog-service
  namespace: central-oondemand-homolog
spec:
  type: NodePort
  selector:
    app: auth-frontend-homolog
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
